### PR TITLE
Missing assets

### PR DESCRIPTION
**Pull request by dkhamsing**
These were missing.. I'm sure you can find better ones :grin:

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hmm `port5.jpg` is a little small

**Comment by matteocrippa** [comment]
Yep, I should have a 512px version... somewhere at work. I have to find that.
Then prob I should add even passwger project, @dkhamsing do you know that?

**Comment by dkhamsing** [comment]
Nope what's that

**Comment by matteocrippa** [comment]
here you are: https://github.com/passwger/passwger-core

it's a 1password app written in nodejs but opensource, still under dev.

**Comment by dkhamsing** [comment]
Ah yeah.. looks real nice
Looks like you're getting close for prerelease

:smile:

**Comment by matteocrippa** [comment]
It would be great, but I'm pretty sure to be a lot far from release, hoping in the meanwhile someone could be interested in, in order to improve it like a real open source project

**Pull request merged**
